stages:
  - build
  - test

include:
  # Build
  - local: '.gitlab/build.yml'

test:terraform:
  stage: test
  script:
    - docker run $TERRAFORM_IMAGE_TAG
  when: manual
  
# test:db-and-s3:
#   stage: test
#   script:
#     - docker compose -f docker-compose.yaml -f docker-compose.test.yaml up client

# deploy:
#   stage: production
#   script:
#     - docker compose up client
#   when: manual