stages:
  - build
  - validate
  - plan
  - apply

include:
  # Build
  - local: '.gitlab/build.yml'

variables:
  TERRAFORM_IMAGE_TAG: $CI_REGISTRY_IMAGE:$TERRAFORM_VERSION
  TERRAFORM_VERSION: 1.2.7
  dir: simple-ec2

image:
  name: hashicorp/terraform:$TERRAFORM_VERSION
  entrypoint:
    - /usr/bin/env
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

before_script:
  - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - rm -rf .terraform
  - terraform --version
  - terraform -chdir=${dir} init
cache:
  key: terraform
  paths:
    - .terraform

validate:
  stage: validate
  script:
    - terraform validate
  
plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual