stages:
  - build
  - validate
  - plan
  - apply
  - destroy

include:
  # Build
  - local: '.gitlab/build.yml'

variables:
  TERRAFORM_IMAGE_TAG: $CI_REGISTRY_IMAGE:$TERRAFORM_VERSION
  TERRAFORM_VERSION: 1.2.7
  dir: simple-ec2

image:
  name: hashicorp/terraform:$TERRAFORM_VERSION
  entrypoint:
    - /usr/bin/env
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

before_script:
  - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - rm -rf .terraform
  - terraform --version
  - terraform -chdir=${dir} init
cache:
  key: terraform
  paths:
    - ${dir}/.terraform

validate:
  stage: validate
  script:
    - terraform -chdir=${dir} validate
  
plan:
  stage: plan
  script:
    - terraform -chdir=${dir} plan -out "planfile"
    - ls -la
    - ls -al simple-ec2
  dependencies:
    - validate
  artifacts:
    paths:
      - ${dir}/planfile

apply:
  stage: apply
  script:
    - terraform -chdir=${dir} apply -input=false "planfile"
    - ls -la
    - ls -al simple-ec2
  dependencies:
    - plan
  when: manual

destroy:
  stage: destroy
  environment:
    name: production
  script:
    - ls -la
    - ls -al simple-ec2
    - terraform -chdir=${dir} destroy -auto-approve
  dependencies:
    - apply
  when: manual
  only:
    - main
