variables:
  TERRAFORM_IMAGE_TAG: $CI_REGISTRY_IMAGE:$TERRAFORM_VERSION
  TERRAFORM_VERSION: 1.2.7

build:terraform:
  image:
    name: docker:latest
  services:
    - docker:dind
  stage: build
  script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg TERRAFORM_VERSION=1.2.7 -t $TERRAFORM_IMAGE_TAG .
    - docker push $TERRAFORM_IMAGE_TAG
  when: manual